// frameworks/svelte/Counter.svelte
<script>
	import { renderLog } from "$lib";

  renderLog("Counter.svelte");
  //runes
  let count = $state(1);
  let double = $derived(count * 2);

  $effect(() => console.log(`[count] changed to: ${count}`))

  const increment = () => count++;

</script>

<div class="counter">
  <p>{count} ({double})</p>
  <button onclick={increment}>Increment</button>
</div>

// frameworks/vue/Counter.vue
<script setup lang="ts">
renderLog("Counter");

const count = ref(1);
const double = computed(() => count.value * 2);

effect(() => console.log(`[count] changed to: ${count.value}`));

function increment() {
  count.value = count.value + 1;
}
</script>

<template>
  <div class="counter">
    <p>{{ count }} ({{ double }})</p>
    <button v-on:click="increment">Increment</button>
  </div>
</template>

<style scoped lang="scss"></style>
